apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '66'
    field.cattle.io/publicEndpoints: >-
      [{"port":31190,"protocol":"TCP","serviceName":"nms4cloud:nms4cloud-pos11report","allNodes":true}]
  creationTimestamp: '2026-02-04T09:31:37Z'
  generation: 88
  labels:
    app: nms4cloud-pos11report
    objectset.rio.cattle.io/hash: 8b029846b1ca0a6faf8225a91d58fd837ed1072c
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:template:
            f:metadata:
              f:annotations:
                f:kubectl.kubernetes.io/restartedAt: {}
      manager: kubectl-rollout
      operation: Update
      time: '2026-04-03T09:49:12Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/publicEndpoints: {}
          f:labels:
            .: {}
            f:app: {}
            f:objectset.rio.cattle.io/hash: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:cattle.io/timestamp: {}
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:containers:
                k:{"name":"nms4cloud-pos11report"}:
                  .: {}
                  f:envFrom: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":9190,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:imagePullSecrets:
                .: {}
                k:{"name":"tencent-ccr-secret"}: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
      manager: rancher
      operation: Update
      time: '2026-08-05T08:43:07Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2026-08-12T05:52:28Z'
  name: nms4cloud-pos11report
  namespace: nms4cloud
  resourceVersion: '27782044'
  uid: 65c4f3d0-8c16-42e6-aad3-46216ef5e954
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nms4cloud-pos11report
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2026-08-05T08:43:07Z'
        kubectl.kubernetes.io/restartedAt: '2026-04-03T17:49:12+08:00'
      labels:
        app: nms4cloud-pos11report
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: nacos
          image: 10.43.92.252/library/nms4cloud-pos11report:latest
          imagePullPolicy: Always
          name: nms4cloud-pos11report
          ports:
            - containerPort: 9190
              name: 9190tcp
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: tencent-ccr-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2026-02-04T09:31:37Z'
      lastUpdateTime: '2026-08-05T08:44:11Z'
      message: >-
        ReplicaSet "nms4cloud-pos11report-847478b5b4" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2026-08-12T05:52:28Z'
      lastUpdateTime: '2026-08-12T05:52:28Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 88
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
