apiVersion: apps/v1
kind: Deployment
metadata:
  name: nms4cloud-bi
  namespace: nms4cloud
  labels:
    app: nms4cloud-bi
spec:
  selector:
    matchLabels:
      app: nms4cloud-bi
  template:
    metadata:
      namespace: nms4cloud
      labels:
        app: nms4cloud-bi
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: nacos
        image: 10.43.92.252/library/nms4cloud-bi:latest
        imagePullPolicy: Always
        name: nms4cloud-bi
        ports:
        - containerPort: 18131
          name: 18131tcp
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 750m
            memory: 1Gi
