apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/business/nacos.yaml
- ../base/cluster/local-path-provisioner.yaml
- ../base/data/mysql.yaml
- ../base/platform/harbor-core.yaml
- ../base/platform/harbor-jobservice.yaml
- ../base/platform/harbor-nginx.yaml
- ../base/platform/harbor-portal.yaml
- ../base/platform/harbor-registry.yaml
- ../base/platform/jenkins.yaml
- ../base/platform/nexus.yaml
