netty:
  host: 192.168.1.119
  port: 30998

nms:
  common:
    api-server: http://${netty.host}:30080

forest:
  variables:
    baseUrl: http://${netty.host}:30080

nms4cloud:
  pay:
    server: https://p.gzjjzhy.com

oss:
  bucketName: chain-pictures-01-1251303505
















