
(()=>{const root=document.querySelector('#pt-005'),studio=root.querySelector('.studio'),surface=root.querySelector('[data-testid="pt005-layout-surface"]'),title=root.querySelector('[data-testid="pt005-layout-title"]'),contract=root.querySelector('[data-testid="pt005-layout-contract"]'),modeValue=root.querySelector('[data-testid="pt005-inspector-mode"]'),field=root.querySelector('[data-testid="pt005-field-customer"]'),statusTitle=root.querySelector('[data-testid="pt005-status-title"]'),statusMessage=root.querySelector('[data-testid="pt005-status-message"]'),dirty=root.querySelector('[data-testid="pt005-dirty-chip"]');let mode='grid',span=2,nested=false;
  const meta={components:['布局组件','可放置'],fields:['业务字段','已绑定'],outline:['页面大纲','结构同步'],issues:['问题','0 错误'],versions:['版本历史','草稿 v12'],data:['数据源','连接正常']};
  function status(a,b){statusTitle.textContent=a;statusMessage.textContent=b}
  function markDirty(message){dirty.textContent='未保存';dirty.className='chip warn';status('布局已更新',message)}
  function render(){root.dataset.layoutMode=mode;surface.dataset.mode=mode;root.querySelectorAll('[data-mode-command]').forEach(b=>b.classList.toggle('on',b.dataset.modeCommand===mode));root.querySelectorAll('[data-layout-asset]').forEach(b=>b.classList.toggle('selected',b.dataset.layoutAsset===mode));const names={grid:'GridLayout',flex:'FlexRow',section:'Section'};title.textContent=names[mode]+' · 单据头';contract.textContent=mode==='grid'?'columns=4 · gap=12':mode==='flex'?'wrap · gap=12':'2 groups · padding=18';modeValue.textContent=names[mode];field.classList.toggle('span-2',mode==='grid'&&span===2);root.querySelector('[data-testid="pt005-span-value"]').textContent=span+' / 4'}
  function setMode(next){mode=next;render();markDirty('已切换为 '+root.querySelector('[data-testid="pt005-inspector-mode"]').textContent)}
  root.querySelectorAll('[data-mode-command]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.modeCommand)));root.querySelectorAll('[data-layout-asset]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.layoutAsset)));
  root.querySelectorAll('.activity [role="tab"]').forEach((b,index,all)=>{b.tabIndex=index? -1:0;b.addEventListener('click',()=>{all.forEach(x=>{x.setAttribute('aria-selected',x===b);x.tabIndex=x===b?0:-1});root.querySelectorAll('.mode-panel').forEach(p=>p.hidden=p.id!==b.getAttribute('aria-controls'));const m=b.dataset.mode;root.querySelector('[data-testid="pt005-left-title"]').textContent=meta[m][0];root.querySelector('[data-testid="pt005-left-state"]').textContent=meta[m][1];if(studio.dataset.assets==='collapsed')studio.dataset.assets='expanded';status('资源区已切换',meta[m][0]+'已打开')});b.addEventListener('keydown',e=>{if(!['ArrowDown','ArrowUp'].includes(e.key))return;e.preventDefault();const n=all[(index+(e.key==='ArrowDown'?1:-1)+all.length)%all.length];n.focus();n.click()})});
  root.querySelector('[data-testid="pt005-span-dec"]').addEventListener('click',()=>{span=Math.max(1,span-1);render();markDirty('客户字段跨度调整为 '+span)});root.querySelector('[data-testid="pt005-span-inc"]').addEventListener('click',()=>{span=Math.min(4,span+1);render();markDirty('客户字段跨度调整为 '+span)});
  root.querySelector('[data-testid="designer-dropzone-section-main-footer"]').addEventListener('click',()=>{nested=!nested;root.dataset.nested=String(nested);root.querySelector('[data-testid="pt005-nested-section"]').hidden=!nested;markDirty(nested?'已创建交付信息 Section':'已移除嵌套 Section')});
  root.querySelector('[data-testid="pt005-columns"]').addEventListener('change',e=>{contract.textContent='columns='+e.target.value+' · gap=12';markDirty('列数调整为 '+e.target.value)});root.querySelector('[data-testid="top-command-save"]').addEventListener('click',()=>{dirty.textContent='已保存';dirty.className='chip ok';status('保存成功','布局 Schema 已写入草稿 v12')});root.querySelector('[data-testid="pt005-command-undo"]').addEventListener('click',()=>{mode='grid';span=2;nested=false;root.querySelector('[data-testid="pt005-nested-section"]').hidden=true;render();status('已撤销','恢复 Grid 4 列、跨度 2')});
  root.querySelector('[data-testid="pt005-assets-collapse"]').addEventListener('click',()=>{studio.dataset.assets=studio.dataset.assets==='collapsed'?'expanded':'collapsed'});root.querySelector('[data-testid="pt005-inspector-collapse"]').addEventListener('click',()=>studio.dataset.inspector='collapsed');root.querySelector('[data-testid="pt005-inspector-expand"]').addEventListener('click',()=>studio.dataset.inspector='expanded');root.querySelectorAll('[data-inspector-tab]').forEach(tab=>tab.addEventListener('click',()=>{root.querySelectorAll('[data-inspector-tab]').forEach(x=>x.setAttribute('aria-selected',x===tab));root.querySelectorAll('[data-inspector-panel]').forEach(x=>x.hidden=x.dataset.inspectorPanel!==tab.dataset.inspectorTab)}));render();if(window.lucide)lucide.createIcons()})();
