function mount(ctx, html) {
  ctx.stage.innerHTML = `<div class="prototype-demo">${html}<output data-state aria-live="polite"></output></div>`;
  const q=(s)=>ctx.stage.querySelector(s),qa=(s)=>[...ctx.stage.querySelectorAll(s)];
  const state=(value)=>{q("[data-state]").textContent=String(value);ctx.setStatus?.(value,value);};
  const on=(s,t,l)=>ctx.on(q(s),t,l);
  return {q,qa,state,on};
}

export function renderStandardForm(ctx){const ui=mount(ctx,`<label>客户名称 <input data-name required value="海风科技"></label><label>联系人 <input data-contact value="林经理"></label><button data-submit>提交客户</button>`);ui.on("[data-submit]","click",()=>ui.state(ui.q("[data-name]").value.trim()?`submitted:${ui.q("[data-name]").value}`:"error:name-required"));ui.state("form:idle");}
export function renderDenseForm(ctx){const ui=mount(ctx,`<div data-dense style="display:grid;grid-template-columns:auto 1fr auto 1fr;gap:4px"><label for="code">编码</label><input id="code" value="C001"><label for="short">简称</label><input id="short" value="海风"></div><button data-density>切换舒适间距</button>`);let dense=true;ui.on("[data-density]","click",()=>{dense=!dense;ui.q("[data-dense]").style.gap=dense?"4px":"16px";ui.state(`density:${dense?"dense":"comfortable"}`);});ui.state("density:dense");}
export function renderDynamicForm(ctx){const ui=mount(ctx,`<form data-dynamic><label>名称 <input></label></form><button data-add-field>按条件添加税号字段</button>`);let added=false;ui.on("[data-add-field]","click",()=>{added=!added;ui.q("[data-tax]")?.remove();if(added){const label=document.createElement("label");label.dataset.tax="";label.textContent="税号 ";const input=document.createElement("input");input.setAttribute("aria-label","税号");label.append(input);ui.q("[data-dynamic]").append(label);}ui.state(`fields:${added?2:1}`);});ui.state("fields:1");}
export function renderSchemaForm(ctx){const ui=mount(ctx,`<label>JSON Schema <textarea data-schema>{"type":"object","properties":{"name":{"type":"string"}}}</textarea></label><button data-validate>校验并渲染</button><div data-rendered></div>`);ui.on("[data-validate]","click",()=>{try{const schema=JSON.parse(ui.q("[data-schema]").value);if(schema.type!=="object"||!schema.properties)throw new Error("schema");ui.q("[data-rendered]").textContent=`已渲染字段：${Object.keys(schema.properties).join(", ")}`;ui.state("schema:valid");}catch{ui.q("[data-rendered]").textContent="Schema 无效，保留上次有效表单";ui.state("schema:invalid");}});ui.state("schema:unvalidated");}
export function renderNestedForm(ctx){const ui=mount(ctx,`<label>客户名称 <input data-path="customer.name" value="海风"></label><fieldset><legend>地址</legend><label>城市 <input data-path="customer.address.city" value="上海"></label></fieldset><button data-path-save>更新嵌套路径</button>`);ui.on("[data-path-save]","click",()=>ui.state(`path:customer.address.city=${ui.q('[data-path="customer.address.city"]').value}`));ui.state("path:unchanged");}
export function renderRepeatableForm(ctx){const ui=mount(ctx,`<div data-lines><div data-line><label>商品 <input value="键盘"></label><button data-remove type="button">删除</button></div></div><button data-add-line>添加明细行</button>`);ui.on("[data-add-line]","click",()=>{const div=document.createElement("div");div.dataset.line="";const input=document.createElement("input");input.setAttribute("aria-label","商品");input.value="显示器";div.append(input);ui.q("[data-lines]").append(div);ui.state(`lines:${ui.qa("[data-line]").length}`);});ui.state("lines:1");}
export function renderMasterDetailForm(ctx){const ui=mount(ctx,`<label>订单客户 <input value="海风科技"></label><table><tbody><tr><td><input data-qty aria-label="数量" type="number" value="2"></td><td><input data-price aria-label="单价" type="number" value="50"></td></tr></tbody></table><button data-total>计算明细总额</button>`);ui.on("[data-total]","click",()=>ui.state(`total:${Number(ui.q("[data-qty]").value)*Number(ui.q("[data-price]").value)}`));ui.state("total:0");}
export function renderWizardForm(ctx){const ui=mount(ctx,`<div data-step-content>第 1 步：基本信息</div><button data-prev disabled>上一步</button><button data-next>下一步</button>`);let step=1;const update=()=>{ui.q("[data-step-content]").textContent=`第 ${step} 步：${["","基本信息","联系信息","确认提交"][step]}`;ui.q("[data-prev]").disabled=step===1;ui.q("[data-next]").disabled=step===3;ui.state(`wizardStep:${step}`);};ui.on("[data-prev]","click",()=>{step=Math.max(1,step-1);update();});ui.on("[data-next]","click",()=>{step=Math.min(3,step+1);update();});update();}
export function renderStepForm(ctx){const ui=mount(ctx,`<label>邮箱 <input data-email></label><button data-step-next>验证并继续</button><div data-step-error></div>`);ui.on("[data-step-next]","click",()=>{const valid=/^[^@]+@[^@]+$/.test(ui.q("[data-email]").value);ui.q("[data-step-error]").textContent=valid?"进入下一步":"邮箱格式错误";ui.state(valid?"step:2":"step:blocked");});ui.state("step:1");}
export function renderTabForm(ctx){const ui=mount(ctx,`<div role="tablist"><button data-tab="base">基本信息</button><button data-tab="finance">财务信息</button></div><label>名称 <input data-dirty></label>`);let active="base",dirty=false;ui.on("[data-dirty]","input",()=>{dirty=true;ui.state(`tab:${active};dirty:true`);});ui.qa("[data-tab]").forEach((tab)=>ctx.on(tab,"click",()=>{active=tab.dataset.tab;ui.state(`tab:${active};dirty:${dirty}`);}));ui.state("tab:base;dirty:false");}
export function renderAccordionForm(ctx){const ui=mount(ctx,`<button data-section aria-expanded="false">联系方式 <span data-badge>1 个错误</span></button><div data-fields hidden><label>手机号 <input data-phone></label></div>`);let open=false;ui.on("[data-section]","click",()=>{open=!open;ui.q("[data-fields]").hidden=!open;ui.q("[data-section]").setAttribute("aria-expanded",String(open));ui.state(`section:${open?"open":"closed"};errors:1`);});ui.state("section:closed;errors:1");}
export function renderConditionalForm(ctx){const ui=mount(ctx,`<label><input type="checkbox" data-company> 企业客户</label><label data-tax hidden>税号 <input></label>`);ui.on("[data-company]","change",()=>{const show=ui.q("[data-company]").checked;ui.q("[data-tax]").hidden=!show;ui.state(`taxVisible:${show}`);});ui.state("taxVisible:false");}
export function renderLinkedForm(ctx){const ui=mount(ctx,`<label>省份 <select data-province><option>上海</option><option>浙江</option></select></label><label>城市 <select data-city aria-label="城市"></select></label><button data-linked-toggle>切换到浙江</button>`);const update=()=>{const cities=ui.q("[data-province]").value==="上海"?["上海市"]:["杭州","宁波"];ui.q("[data-city]").replaceChildren(...cities.map((text)=>{const option=document.createElement("option");option.textContent=text;return option;}));ui.state(`cities:${cities.join(",")}`);};ui.on("[data-province]","change",update);ui.on("[data-linked-toggle]","click",()=>{ui.q("[data-province]").value=ui.q("[data-province]").value==="上海"?"浙江":"上海";update();});update();}
export function renderCalculatedForm(ctx){const ui=mount(ctx,`<label>数量 <input data-qty type="number" value="2"></label><label>单价 <input data-price type="number" value="30"></label><output data-amount></output><button data-calc-next>数量 +1</button>`);const calc=()=>{const amount=Number(ui.q("[data-qty]").value)*Number(ui.q("[data-price]").value);ui.q("[data-amount]").textContent=`金额：${amount}`;ui.state(`amount:${amount}`);};ui.on("[data-qty]","input",calc);ui.on("[data-price]","input",calc);ui.on("[data-calc-next]","click",()=>{ui.q("[data-qty]").value=String(Number(ui.q("[data-qty]").value)+1);calc();});calc();}
export function renderValidationForm(ctx){const ui=mount(ctx,`<label>开始日期 <input data-start type="date" value="2026-07-10"></label><label>结束日期 <input data-end type="date" value="2026-07-08"></label><button data-check>校验组合规则</button>`);ui.on("[data-check]","click",()=>{const valid=ui.q("[data-start]").value<=ui.q("[data-end]").value;ui.state(valid?"validation:pass":"validation:end-before-start");});ui.state("validation:unchecked");}
export function renderAsyncValidationForm(ctx){const ui=mount(ctx,`<label>用户名 <input data-username value="admin"></label><button data-async-check>异步检查</button>`);let sequence=0;ui.on("[data-async-check]","click",()=>{const current=++sequence,name=ui.q("[data-username]").value;ui.state("async:pending");ctx.timeout(()=>{if(current!==sequence)return;ui.state(name.toLowerCase()==="admin"?"async:unavailable":"async:available");},120);});ui.state("async:idle");}
export function renderRealtimeValidationForm(ctx){const ui=mount(ctx,`<label>密码 <input data-password type="password"></label><meter data-strength min="0" max="3" value="0"></meter><button data-strong-password>填入强密码</button>`);const validate=()=>{const value=ui.q("[data-password]").value,score=(value.length>=8?1:0)+(/[A-Z]/.test(value)?1:0)+(/\d/.test(value)?1:0);ui.q("[data-strength]").value=score;ui.state(`strength:${score}`);};ui.on("[data-password]","input",validate);ui.on("[data-strong-password]","click",()=>{ui.q("[data-password]").value="StrongPwd8";validate();});ui.state("strength:0");}
export function renderDraftForm(ctx){const ui=mount(ctx,`<label>方案名称 <input data-draft></label><output data-saved></output><button data-edit-draft>模拟编辑</button>`);let version=0;const save=()=>{ui.state("draft:saving");ctx.timeout(()=>{version+=1;ui.q("[data-saved]").textContent=`草稿 v${version} 已保存`;ui.state(`draft:saved:${version}`);},100);};ui.on("[data-draft]","input",save);ui.on("[data-edit-draft]","click",()=>{ui.q("[data-draft]").value="新方案";save();});ui.state("draft:clean");}
export function renderMultiPageForm(ctx){const ui=mount(ctx,`<progress data-progress max="4" value="1"></progress><div data-page>第 1 页 / 4</div><button data-page-next>下一页</button>`);let page=1;ui.on("[data-page-next]","click",()=>{page=page===4?1:page+1;ui.q("[data-progress]").value=page;ui.q("[data-page]").textContent=`第 ${page} 页 / 4`;ui.state(`page:${page}`);});ui.state("page:1");}
export function renderSurveyForm(ctx){const ui=mount(ctx,`<fieldset><legend>服务满意度</legend><label><input type="radio" name="score" value="1">1</label><label><input type="radio" name="score" value="3">3</label><label><input type="radio" name="score" value="5">5</label></fieldset>`);ui.qa('input[name="score"]').forEach((input)=>ctx.on(input,"change",()=>ui.state(`score:${input.value}`)));ui.state("score:none");}
export function renderConversationalForm(ctx){const ui=mount(ctx,`<div data-chat><p>你的公司名称是什么？</p></div><label>回答 <input data-answer></label><button data-answer-next>发送并继续</button>`);let question=1;ui.on("[data-answer-next]","click",()=>{const p=document.createElement("p");p.textContent=`你：${ui.q("[data-answer]").value}`;ui.q("[data-chat]").append(p);question+=1;const next=document.createElement("p");next.textContent=question===2?"公司规模是多少？":"谢谢，信息已完成。";ui.q("[data-chat]").append(next);ui.state(`question:${question}`);});ui.state("question:1");}
export function renderMatrixQuestionForm(ctx){const ui=mount(ctx,`<table><tbody><tr><th>速度</th><td><input type="radio" name="speed" value="good" aria-label="速度满意"></td></tr><tr><th>稳定性</th><td><input type="radio" name="stable" value="good" aria-label="稳定性满意"></td></tr></tbody></table><button data-matrix-check>检查完成度</button>`);ui.on("[data-matrix-check]","click",()=>{const answered=ui.qa('input[type="radio"]:checked').length;ui.state(`answered:${answered}/2`);});ui.state("matrix:unchecked");}
export function renderUploadForm(ctx){const ui=mount(ctx,`<input type="file" data-file aria-label="选择文件"><ul data-queue></ul><button data-mock-upload>加入示例文件</button>`);ui.on("[data-mock-upload]","click",()=>{const li=document.createElement("li");li.textContent="合同.pdf — 上传中 50%";ui.q("[data-queue]").append(li);ui.state(`queue:${ui.qa("[data-queue] li").length};progress:50`);});ui.state("queue:0");}
export function renderSignatureForm(ctx){const ui=mount(ctx,`<canvas data-signature width="280" height="100" style="border:1px solid #aaa"></canvas><button data-stroke>模拟签一笔</button><button data-clear>清除签名</button>`);let strokes=0;ui.on("[data-stroke]","click",()=>{strokes+=1;const pen=ui.q("[data-signature]").getContext("2d");pen.beginPath();pen.moveTo(20,50);pen.lineTo(80+strokes*20,30);pen.stroke();ui.state(`strokes:${strokes}`);});ui.on("[data-clear]","click",()=>{strokes=0;ui.q("[data-signature]").getContext("2d").clearRect(0,0,280,100);ui.state("strokes:0");});ui.state("strokes:0");}
export function renderDateRangeForm(ctx){const ui=mount(ctx,`<label>开始 <input data-start type="date" value="2026-07-14"></label><label>结束 <input data-end type="date" value="2026-07-20"></label><button data-range>计算天数</button>`);ui.on("[data-range]","click",()=>{const start=new Date(ui.q("[data-start]").value),end=new Date(ui.q("[data-end]").value),days=(end-start)/86400000;ui.state(days>=0?`rangeDays:${days}`:"range:invalid");});ui.state("range:unchecked");}
export function renderAddressForm(ctx){const ui=mount(ctx,`<label>省 <select data-province><option>浙江</option><option>江苏</option></select></label><label>市 <select data-city></select></label><label>区 <select data-district></select></label><button data-address-next>切换省份</button>`);const update=()=>{const city=ui.q("[data-province]").value==="浙江"?"杭州":"南京";ui.q("[data-city]").replaceChildren(new Option(city));ui.q("[data-district]").replaceChildren(new Option(city==="杭州"?"西湖区":"玄武区"));ui.state(`address:${ui.q("[data-province]").value}/${city}/${ui.q("[data-district]").value}`);};ui.on("[data-province]","change",update);ui.on("[data-address-next]","click",()=>{ui.q("[data-province]").value=ui.q("[data-province]").value==="浙江"?"江苏":"浙江";update();});update();}
export function renderApprovalForm(ctx){const ui=mount(ctx,`<label>申请金额 <input data-amount type="number" value="1200"></label><label>审批意见 <textarea data-comment></textarea></label><button data-approve>通过</button><button data-reject>驳回</button>`);ui.on("[data-approve]","click",()=>ui.state("approval:approved"));ui.on("[data-reject]","click",()=>ui.state(ui.q("[data-comment]").value.trim()?"approval:rejected":"approval:comment-required"));ui.state("approval:pending");}
export function renderVersionForm(ctx){const ui=mount(ctx,`<select data-version aria-label="选择版本"><option value="v1">v1 原值</option><option value="v2">v2 新值</option></select><div data-diff>选择版本查看差异</div><button data-version-next>比较 v2</button>`);const compare=()=>{const version=ui.q("[data-version]").value;ui.q("[data-diff]").textContent=version==="v1"?"名称：海风":"名称：海风科技（新增“科技”）";ui.state(`version:${version}`);};ui.on("[data-version]","change",compare);ui.on("[data-version-next]","click",()=>{ui.q("[data-version]").value=ui.q("[data-version]").value==="v1"?"v2":"v1";compare();});ui.state("version:v1");}
export function renderFormDesigner(ctx){const ui=mount(ctx,`<div style="display:flex;gap:12px"><div><button data-field="email">邮箱字段</button><button data-field="date">日期字段</button></div><form data-canvas></form></div>`);ui.qa("[data-field]").forEach((button)=>ctx.on(button,"click",()=>{const label=document.createElement("label");label.textContent=`${button.textContent} `;const input=document.createElement("input");input.type=button.dataset.field==="date"?"date":"email";input.setAttribute("aria-label",button.textContent);label.append(input);ui.q("[data-canvas]").append(label);ui.state(`placed:${button.dataset.field}`);}));ui.state("placed:none");}
export function renderRuntimeForm(ctx){const ui=mount(ctx,`<div data-mode>设计态：客户表单</div><button data-preview>进入运行时预览</button><form data-runtime hidden><label>客户 <input data-customer value="海风科技"></label><button type="button" data-runtime-submit>提交</button></form>`);ui.on("[data-preview]","click",()=>{ui.q("[data-runtime]").hidden=false;ui.q("[data-mode]").textContent="运行态预览";ui.state("runtime:preview");});ui.on("[data-runtime-submit]","click",()=>ui.state(`runtime:submitted:${ui.q("[data-customer]").value}`));ui.state("runtime:design");}

export const formRenderers={"04:standard-form":renderStandardForm,"04:dense-form":renderDenseForm,"04:dynamic-form":renderDynamicForm,"04:schema-form":renderSchemaForm,"04:nested-form":renderNestedForm,"04:repeatable-form":renderRepeatableForm,"04:master-detail-form":renderMasterDetailForm,"04:wizard-form":renderWizardForm,"04:step-form":renderStepForm,"04:tab-form":renderTabForm,"04:accordion-form":renderAccordionForm,"04:conditional-form":renderConditionalForm,"04:linked-form":renderLinkedForm,"04:calculated-form":renderCalculatedForm,"04:validation-form":renderValidationForm,"04:async-validation-form":renderAsyncValidationForm,"04:realtime-validation-form":renderRealtimeValidationForm,"04:draft-form":renderDraftForm,"04:multi-page-form":renderMultiPageForm,"04:survey-form":renderSurveyForm,"04:conversational-form":renderConversationalForm,"04:matrix-question-form":renderMatrixQuestionForm,"04:upload-form":renderUploadForm,"04:signature-form":renderSignatureForm,"04:date-range-form":renderDateRangeForm,"04:address-form":renderAddressForm,"04:approval-form":renderApprovalForm,"04:version-form":renderVersionForm,"04:form-designer":renderFormDesigner,"04:runtime-form":renderRuntimeForm};
export const renderers04=formRenderers;
export default formRenderers;
