export const categoryNumber = "08";
function workbench(ctx, title, ...children) { return ctx.el("div", { className: "demo col" }, ctx.el("h3", { text: title }), ...children); }
function state(ctx, text) { return ctx.el("div", { className: "status", text }); }
function renderPageDesigner(ctx) { const view = state(ctx, "画布：单列；组件 1"); const add = ctx.button("放置双栏容器", "page-place"); ctx.on(add, "click", () => { view.textContent = "画布：双栏；左栏表格，右栏详情"; ctx.setStatus("页面布局已改变", "layout:two-column"); }); ctx.stage.append(workbench(ctx, "页面布局设计", view, add)); return {}; }
function renderFormDesigner(ctx) { const fields = state(ctx, "字段：客户名称"); const add = ctx.button("放置金额字段", "form-place"); ctx.on(add, "click", () => { fields.textContent = "字段：客户名称、金额（数值/必填）"; ctx.setStatus("表单字段增至 2 个", "fields:2"); }); ctx.stage.append(workbench(ctx, "表单设计", fields, add)); return {}; }
function renderReportDesigner(ctx) { const axes = state(ctx, "维度：月份；度量：销售额"); const add = ctx.button("添加地区维度", "report-dimension"); ctx.on(add, "click", () => { axes.textContent = "维度：地区 > 月份；度量：销售额"; ctx.setStatus("报表维度增至 2 个", "dimensions:2"); }); ctx.stage.append(workbench(ctx, "报表维度与度量", axes, add)); return {}; }
function renderDashboardDesigner(ctx) { const widgets = state(ctx, "组件：销售额卡片"); const bind = ctx.button("绑定趋势图数据", "dashboard-bind"); ctx.on(bind, "click", () => { widgets.textContent = "销售额卡片 + 月度趋势图（12 点）"; ctx.setStatus("仪表盘组件增至 2 个", "widgets:2"); }); ctx.stage.append(workbench(ctx, "仪表盘", widgets, bind)); return {}; }
function renderMobilePageDesigner(ctx) { const phone = state(ctx, "设备 390×844；安全区可见"); const add = ctx.button("添加底部操作栏", "mobile-bar"); ctx.on(add, "click", () => { phone.textContent = "底栏已吸附于安全区上方，主内容可滚动"; ctx.setStatus("移动安全区布局完成", "mobile:safe-bar"); }); ctx.stage.append(workbench(ctx, "移动页设计", phone, add)); return {}; }
function renderDataSourceDesigner(ctx) { const connection = state(ctx, "连接 CRM：未测试"); const test = ctx.button("测试连接", "source-test"); ctx.on(test, "click", () => { connection.textContent = "CRM 连接成功；延迟 42ms；表 18"; ctx.setStatus("数据源连接成功", "source:connected"); }); ctx.stage.append(workbench(ctx, "数据源连接", connection, test)); return {}; }
function renderEventDesigner(ctx) { const chain = state(ctx, "onSubmit → validate"); const append = ctx.button("追加 sendRequest", "event-add"); ctx.on(append, "click", () => { chain.textContent = "onSubmit → validate → sendRequest"; ctx.setStatus("事件链增至 3 步", "events:3"); }); ctx.stage.append(workbench(ctx, "事件链", chain, append)); return {}; }
function renderActionDesigner(ctx) { const config = state(ctx, "动作：打开页面；route 未配置"); const configure = ctx.button("配置客户详情路由", "action-config"); ctx.on(configure, "click", () => { config.textContent = "打开 /customer/:id，参数 id={{record.id}}"; ctx.setStatus("动作参数已配置", "action:configured"); }); ctx.stage.append(workbench(ctx, "动作参数", config, configure)); return {}; }
function renderExpressionDesigner(ctx) { const expression = ctx.el("input", { value: "amount > 10000", "aria-label": "可见性表达式" }); const out = state(ctx, "amount=12000"); const test = ctx.button("测试表达式", "expression-run"); ctx.on(test, "click", () => { out.textContent = "结果 true；组件可见"; ctx.setStatus("表达式测试为 true", "expression:true"); }); ctx.stage.append(workbench(ctx, "表达式测试", expression, out, test)); return {}; }
function renderThemeDesigner(ctx) { const tokens = state(ctx, "--brand: #356f9f"); const change = ctx.button("切换高对比主题", "theme-switch"); ctx.on(change, "click", () => { tokens.textContent = "--brand: #0b57d0；--surface: #ffffff；对比度 7.2"; ctx.setStatus("高对比主题已应用", "theme:contrast"); }); ctx.stage.append(workbench(ctx, "主题令牌", tokens, change)); return {}; }
function renderComponentBuilder(ctx) { const api = state(ctx, "Props: title；Slots: default"); const add = ctx.button("添加 loading 属性", "component-prop"); ctx.on(add, "click", () => { api.textContent = "Props: title, loading；事件: retry"; ctx.setStatus("组件 API 已扩展", "component:loading"); }); ctx.stage.append(workbench(ctx, "组件构建器", api, add)); return {}; }
function renderTemplateManager(ctx) { const template = state(ctx, "模板：客户详情 v3"); const instantiate = ctx.button("从模板实例化", "template-create"); ctx.on(instantiate, "click", () => { template.textContent = "已创建 页面-客户详情-副本；模板版本仍为 v3"; ctx.setStatus("模板实例已创建", "template:instantiated"); }); ctx.stage.append(workbench(ctx, "页面模板", template, instantiate)); return {}; }
function renderPageTree(ctx) { const tree = state(ctx, "应用 / 客户 / 客户详情"); const move = ctx.button("将客户详情移到销售下", "page-reparent"); ctx.on(move, "click", () => { tree.textContent = "应用 / 销售 / 客户详情；路由引用已更新"; ctx.setStatus("页面节点已重挂载", "tree:reparented"); }); ctx.stage.append(workbench(ctx, "页面树", tree, move)); return {}; }
function renderNavigationDesigner(ctx) { const route = state(ctx, "客户 → /customers"); const edit = ctx.button("修改为 /crm/customers", "nav-route"); ctx.on(edit, "click", () => { route.textContent = "客户 → /crm/customers；权限 crm.read"; ctx.setStatus("导航路由已更新", "route:/crm/customers"); }); ctx.stage.append(workbench(ctx, "导航设计", route, edit)); return {}; }
function renderResponsiveDesigner(ctx) { const preview = state(ctx, "Desktop 1440：三栏"); const mobile = ctx.button("切换 Mobile 390", "device-mobile"); ctx.on(mobile, "click", () => { preview.textContent = "Mobile 390：单栏；侧栏折叠；底部操作可达"; ctx.setStatus("设备预览切到移动端", "device:mobile"); }); ctx.stage.append(workbench(ctx, "响应式设计", preview, mobile)); return {}; }
function renderRuntimePreview(ctx) { const runtime = state(ctx, "设计数据未提交"); const submit = ctx.button("提交预览表单", "runtime-submit"); ctx.on(submit, "click", () => { runtime.textContent = "运行时校验通过；模拟记录 ID PREVIEW-1"; ctx.setStatus("运行时预览提交成功", "runtime:submitted"); }); ctx.stage.append(workbench(ctx, "运行时预览", runtime, submit)); return {}; }

function renderSchemaEditor(ctx) {
  const source = ctx.el("textarea", { rows: 6, "aria-label": "页面 Schema", value: "{\"type\":\"page\",\"children\":[]}" }); const lastValid = state(ctx, "上一个有效版本：page / 0 children"); const validate = ctx.button("校验 Schema", "schema-validate");
  ctx.on(validate, "click", () => { try { const value = JSON.parse(source.value); if (value.type !== "page") throw new Error(); lastValid.textContent = `有效：${value.type} / ${(value.children || []).length} children`; ctx.setStatus("Schema 校验通过", "schema:valid"); } catch { lastValid.textContent = "校验失败；保留上一个有效版本：page / 0 children"; ctx.setStatus("Schema 校验失败", "schema:error"); } }); ctx.stage.append(workbench(ctx, "Schema 与 last-valid", source, lastValid, validate)); return {};
}
function renderVersionManager(ctx) { const history = state(ctx, "当前 v7；草稿有 3 处修改"); const create = ctx.button("生成 v8 修订", "version-create"); ctx.on(create, "click", () => { history.textContent = "v8 已创建；可比较 v7 ↔ v8；v7 未覆盖"; ctx.setStatus("页面版本 v8 已创建", "version:v8"); }); ctx.stage.append(workbench(ctx, "页面版本", history, create)); return {}; }

function renderPublishConsole(ctx) {
  const environment = ctx.el("select", { "aria-label": "发布环境" }, ctx.el("option", { value: "staging", text: "预发布" }), ctx.el("option", { value: "production", text: "生产" })); const out = state(ctx, "前置校验未运行"); const publish = ctx.button("校验并发布", "publish-run");
  ctx.on(publish, "click", () => { out.textContent = `${environment.value}：前置校验通过，发布 0%`; ctx.setStatus("发布进行中", "publish:running"); ctx.timeout(() => { out.textContent = `${environment.value}：发布 100%，健康检查通过`; ctx.setStatus("发布成功", "publish:success"); }, 100); }); ctx.stage.append(workbench(ctx, "发布控制台", environment, out, publish)); return {};
}
function renderDesignSystemManager(ctx) { const library = state(ctx, "Button v2；Input v4"); const deprecate = ctx.button("弃用 Button v1", "system-deprecate"); ctx.on(deprecate, "click", () => { library.textContent = "Button v1 deprecated → 迁移 Button v2；影响页面 6"; ctx.setStatus("旧组件已标记弃用", "system:deprecated-v1"); }); ctx.stage.append(workbench(ctx, "设计系统管理", library, deprecate)); return {}; }

export const renderers08 = Object.freeze({
  "08:page-designer": renderPageDesigner, "08:form-designer": renderFormDesigner, "08:report-designer": renderReportDesigner,
  "08:dashboard-designer": renderDashboardDesigner, "08:mobile-page-designer": renderMobilePageDesigner, "08:data-source-designer": renderDataSourceDesigner,
  "08:event-designer": renderEventDesigner, "08:action-designer": renderActionDesigner, "08:expression-designer": renderExpressionDesigner,
  "08:theme-designer": renderThemeDesigner, "08:component-builder": renderComponentBuilder, "08:template-manager": renderTemplateManager,
  "08:page-tree": renderPageTree, "08:navigation-designer": renderNavigationDesigner, "08:responsive-designer": renderResponsiveDesigner,
  "08:runtime-preview": renderRuntimePreview, "08:schema-editor": renderSchemaEditor, "08:version-manager": renderVersionManager,
  "08:publish-console": renderPublishConsole, "08:design-system-manager": renderDesignSystemManager,
});
export const renderers = renderers08;
