apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-maven-cache
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  # 如果有 StorageClass，可以指定
  # storageClassName: nfs-client
