CREATE TABLE IF NOT EXISTS `crm_consume_coupon_op_record` (
  `pid` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `mid` BIGINT NOT NULL COMMENT '商户ID',
  `sid` BIGINT NOT NULL COMMENT '门店ID',
  `lid` BIGINT NOT NULL COMMENT '业务逻辑主键',
  `round_key` VARCHAR(128) NOT NULL COMMENT 'POS赠券轮次幂等键',
  `order_id` VARCHAR(64) DEFAULT NULL COMMENT 'POS外部订单号',
  `card_lid` BIGINT DEFAULT NULL COMMENT '会员卡LID',
  `card_no` VARCHAR(64) DEFAULT NULL COMMENT '会员卡号',
  `phone` VARCHAR(32) DEFAULT NULL COMMENT 'CRM会员手机号',
  `status_` INT NOT NULL COMMENT '状态：1-待处理，2-已发券，3-未命中，4-已撤销，5-失败',
  `rule_lid` BIGINT DEFAULT NULL COMMENT '消费赠券规则LID',
  `coupon_lid` BIGINT DEFAULT NULL COMMENT '券模板LID',
  `coupon_num` INT DEFAULT NULL COMMENT '发券数量',
  `coupon_order_lids_json` TEXT COMMENT '券订单LID列表JSON',
  `request_json` TEXT COMMENT '发券请求快照JSON',
  `response_json` TEXT COMMENT '最近一次响应快照JSON',
  `error_msg` TEXT COMMENT '最近一次失败原因',
  `grant_time` DATETIME DEFAULT NULL COMMENT '成功发券时间',
  `revoke_time` DATETIME DEFAULT NULL COMMENT '成功撤销时间',
  `revision` INT DEFAULT NULL COMMENT '乐观锁',
  `created_by` VARCHAR(32) DEFAULT NULL COMMENT '创建人',
  `created_time` DATETIME DEFAULT NULL COMMENT '创建时间',
  `updated_by` VARCHAR(32) DEFAULT NULL COMMENT '更新人',
  `updated_time` DATETIME DEFAULT NULL COMMENT '更新时间',
  `deleted` TINYINT DEFAULT 0 COMMENT '是否删除',
  PRIMARY KEY (`pid`),
  UNIQUE KEY `uk_crm_consume_coupon_op_lid` (`lid`),
  UNIQUE KEY `uk_crm_consume_coupon_op_round` (`mid`, `sid`, `round_key`, `deleted`),
  KEY `idx_crm_consume_coupon_op_order` (`mid`, `order_id`),
  KEY `idx_crm_consume_coupon_op_status` (`status_`)
) COMMENT='CRM消费赠券POS轮次幂等记录';
