create table lc_meta_tenant (
  id bigint not null comment '雪花主键',
  tenant_id bigint not null comment '租户ID',
  code varchar(64) not null comment '租户编码',
  name varchar(128) not null comment '租户名称',
  config json null comment '带_v的租户配置JSON',
  revision bigint not null default 0 comment '乐观锁版本',
  deleted tinyint not null default 0 comment '软删除标记：0否，1是',
  deleted_at datetime(3) null comment '删除时间',
  delete_token bigint not null default 0 comment '软删除唯一墓碑值',
  create_time datetime(3) not null comment '创建时间',
  create_by bigint not null comment '创建人用户ID',
  update_time datetime(3) not null comment '更新时间',
  update_by bigint not null comment '更新人用户ID',
  primary key (id),
  unique key uk_lc_meta_tenant_code_alive (tenant_id, code, delete_token)
) comment='元数据租户表';

create table lc_meta_workspace (
  id bigint not null comment '雪花主键',
  tenant_id bigint not null comment '租户ID',
  code varchar(64) not null comment '工作区编码',
  name varchar(128) not null comment '工作区名称',
  config json null comment '带_v的工作区配置JSON',
  revision bigint not null default 0 comment '乐观锁版本',
  deleted tinyint not null default 0 comment '软删除标记：0否，1是',
  deleted_at datetime(3) null comment '删除时间',
  delete_token bigint not null default 0 comment '软删除唯一墓碑值',
  create_time datetime(3) not null comment '创建时间',
  create_by bigint not null comment '创建人用户ID',
  update_time datetime(3) not null comment '更新时间',
  update_by bigint not null comment '更新人用户ID',
  primary key (id),
  unique key uk_lc_meta_workspace_code_alive (tenant_id, code, delete_token)
) comment='元数据工作区表';

create table lc_meta_app (
  id bigint not null comment '雪花主键',
  tenant_id bigint not null comment '租户ID',
  workspace_id bigint null comment '工作区ID',
  code varchar(64) not null comment '应用编码',
  name varchar(128) not null comment '应用名称',
  config json null comment '带_v的应用配置JSON',
  revision bigint not null default 0 comment '乐观锁版本',
  deleted tinyint not null default 0 comment '软删除标记：0否，1是',
  deleted_at datetime(3) null comment '删除时间',
  delete_token bigint not null default 0 comment '软删除唯一墓碑值',
  create_time datetime(3) not null comment '创建时间',
  create_by bigint not null comment '创建人用户ID',
  update_time datetime(3) not null comment '更新时间',
  update_by bigint not null comment '更新人用户ID',
  primary key (id),
  unique key uk_lc_meta_app_code_alive (tenant_id, code, delete_token)
) comment='元数据应用表';

create table lc_meta_object (
  id bigint not null comment '雪花主键',
  tenant_id bigint not null comment '租户ID',
  app_id bigint not null comment '应用ID',
  code varchar(64) not null comment '对象编码',
  name varchar(128) not null comment '对象名称',
  table_name varchar(128) not null comment '动态物理表名',
  object_type tinyint not null comment '对象类型编码',
  object_category varchar(32) not null default 'custom' comment '对象分类',
  source_kind varchar(32) not null default 'customer' comment '元数据来源层',
  base_object_code varchar(64) null comment '扩展层基准对象编码',
  extension_policy varchar(32) not null default 'none' comment '扩展策略',
  status tinyint not null comment '对象状态编码',
  fields json not null comment '带_v的字段定义JSON',
  relations json null comment '带_v的关系定义JSON',
  states json null comment '带_v的状态定义JSON',
  actions json null comment '带_v的动作定义JSON',
  rules json null comment '带_v的规则定义JSON',
  options json null comment '带_v的对象配置JSON',
  revision bigint not null default 0 comment '乐观锁版本',
  deleted tinyint not null default 0 comment '软删除标记：0否，1是',
  deleted_at datetime(3) null comment '删除时间',
  delete_token bigint not null default 0 comment '软删除唯一墓碑值',
  create_time datetime(3) not null comment '创建时间',
  create_by bigint not null comment '创建人用户ID',
  update_time datetime(3) not null comment '更新时间',
  update_by bigint not null comment '更新人用户ID',
  primary key (id),
  unique key uk_lc_meta_object_app_code_alive (tenant_id, app_id, code, delete_token),
  key idx_lc_meta_object_tenant_app_status (tenant_id, app_id, status)
) comment='元数据对象聚合表';

create table lc_meta_page (
  id bigint not null comment '雪花主键',
  tenant_id bigint not null comment '租户ID',
  app_id bigint not null comment '应用ID',
  code varchar(64) not null comment '页面编码',
  name varchar(128) not null comment '页面名称',
  views json not null comment '带_v的页面视图JSON',
  revision bigint not null default 0 comment '乐观锁版本',
  deleted tinyint not null default 0 comment '软删除标记：0否，1是',
  deleted_at datetime(3) null comment '删除时间',
  delete_token bigint not null default 0 comment '软删除唯一墓碑值',
  create_time datetime(3) not null comment '创建时间',
  create_by bigint not null comment '创建人用户ID',
  update_time datetime(3) not null comment '更新时间',
  update_by bigint not null comment '更新人用户ID',
  primary key (id),
  unique key uk_lc_meta_page_app_code_alive (tenant_id, app_id, code, delete_token)
) comment='元数据页面聚合表';

create table lc_meta_role (
  id bigint not null comment '雪花主键',
  tenant_id bigint not null comment '租户ID',
  app_id bigint not null comment '应用ID',
  code varchar(64) not null comment '角色编码',
  name varchar(128) not null comment '角色名称',
  permissions json not null comment '带_v的权限JSON',
  revision bigint not null default 0 comment '乐观锁版本',
  deleted tinyint not null default 0 comment '软删除标记：0否，1是',
  deleted_at datetime(3) null comment '删除时间',
  delete_token bigint not null default 0 comment '软删除唯一墓碑值',
  create_time datetime(3) not null comment '创建时间',
  create_by bigint not null comment '创建人用户ID',
  update_time datetime(3) not null comment '更新时间',
  update_by bigint not null comment '更新人用户ID',
  primary key (id),
  unique key uk_lc_meta_role_app_code_alive (tenant_id, app_id, code, delete_token)
) comment='元数据角色聚合表';

create table lc_meta_datasource (
  id bigint not null comment '雪花主键',
  tenant_id bigint not null comment '租户ID',
  app_id bigint not null comment '应用ID',
  code varchar(64) not null comment '数据源编码',
  name varchar(128) not null comment '数据源名称',
  config json not null comment '带_v的数据源配置JSON',
  revision bigint not null default 0 comment '乐观锁版本',
  deleted tinyint not null default 0 comment '软删除标记：0否，1是',
  deleted_at datetime(3) null comment '删除时间',
  delete_token bigint not null default 0 comment '软删除唯一墓碑值',
  create_time datetime(3) not null comment '创建时间',
  create_by bigint not null comment '创建人用户ID',
  update_time datetime(3) not null comment '更新时间',
  update_by bigint not null comment '更新人用户ID',
  primary key (id),
  unique key uk_lc_meta_datasource_app_code_alive (tenant_id, app_id, code, delete_token)
) comment='元数据数据源聚合表';

create table lc_meta_version (
  id bigint not null comment '雪花主键',
  tenant_id bigint not null comment '租户ID',
  app_id bigint not null comment '应用ID',
  version_no varchar(64) not null comment '版本号',
  publish_status varchar(32) not null comment '发布状态编码',
  snapshot json not null comment '带_v的应用全量元数据快照JSON',
  published_at datetime(3) null comment '发布时间',
  revision bigint not null default 0 comment '乐观锁版本',
  deleted tinyint not null default 0 comment '软删除标记：0否，1是',
  deleted_at datetime(3) null comment '删除时间',
  delete_token bigint not null default 0 comment '软删除唯一墓碑值',
  create_time datetime(3) not null comment '创建时间',
  create_by bigint not null comment '创建人用户ID',
  update_time datetime(3) not null comment '更新时间',
  update_by bigint not null comment '更新人用户ID',
  primary key (id),
  unique key uk_lc_meta_version_app_version_alive (tenant_id, app_id, version_no, delete_token),
  key idx_lc_meta_version_status (tenant_id, app_id, publish_status)
) comment='元数据版本表';

create table lc_meta_plugin (
  id bigint not null comment '雪花主键',
  tenant_id bigint not null comment '租户ID',
  app_id bigint not null comment '应用ID',
  code varchar(64) not null comment '插件编码',
  name varchar(128) not null comment '插件名称',
  config json not null comment '带_v的插件配置JSON',
  revision bigint not null default 0 comment '乐观锁版本',
  deleted tinyint not null default 0 comment '软删除标记：0否，1是',
  deleted_at datetime(3) null comment '删除时间',
  delete_token bigint not null default 0 comment '软删除唯一墓碑值',
  create_time datetime(3) not null comment '创建时间',
  create_by bigint not null comment '创建人用户ID',
  update_time datetime(3) not null comment '更新时间',
  update_by bigint not null comment '更新人用户ID',
  primary key (id),
  unique key uk_lc_meta_plugin_app_code_alive (tenant_id, app_id, code, delete_token)
) comment='元数据插件聚合表';

create table lc_meta_ref (
  id bigint not null comment '雪花主键',
  tenant_id bigint not null comment '租户ID',
  app_id bigint not null comment '应用ID',
  source_type varchar(32) not null comment '来源类型',
  source_code varchar(128) not null comment '来源编码',
  source_path varchar(256) not null comment '来源路径',
  ref_type varchar(32) not null comment '引用类型',
  target_type varchar(32) not null comment '目标类型',
  target_code varchar(128) not null comment '目标编码',
  detail json null comment '引用详情JSON',
  revision bigint not null default 0 comment '乐观锁版本',
  deleted tinyint not null default 0 comment '软删除标记：0否，1是',
  deleted_at datetime(3) null comment '删除时间',
  delete_token bigint not null default 0 comment '软删除唯一墓碑值',
  create_time datetime(3) not null comment '创建时间',
  create_by bigint not null comment '创建人用户ID',
  update_time datetime(3) not null comment '更新时间',
  update_by bigint not null comment '更新人用户ID',
  primary key (id),
  key idx_lc_meta_ref_source (tenant_id, app_id, source_type, source_code),
  key idx_lc_meta_ref_target (tenant_id, app_id, target_type, target_code),
  key idx_lc_meta_ref_type (tenant_id, app_id, ref_type)
) comment='元数据引用索引表';

create table lc_rt_physical_schema (
  id bigint not null comment '雪花主键',
  tenant_id bigint not null comment '租户ID',
  app_id bigint not null comment '应用ID',
  object_code varchar(64) not null comment '对象编码',
  table_name varchar(128) not null comment '物理表名',
  schema_json json not null comment '已登记物理结构JSON',
  schema_hash varchar(128) not null comment '物理结构哈希',
  revision bigint not null default 0 comment '乐观锁版本',
  deleted tinyint not null default 0 comment '软删除标记：0否，1是',
  deleted_at datetime(3) null comment '删除时间',
  delete_token bigint not null default 0 comment '软删除唯一墓碑值',
  create_time datetime(3) not null comment '创建时间',
  create_by bigint not null comment '创建人用户ID',
  update_time datetime(3) not null comment '更新时间',
  update_by bigint not null comment '更新人用户ID',
  primary key (id),
  unique key uk_lc_rt_physical_schema_object_alive (tenant_id, app_id, object_code, delete_token)
) comment='运行时物理结构登记表';

create table lc_rt_ddl_log (
  id bigint not null comment '雪花主键',
  tenant_id bigint not null comment '租户ID',
  app_id bigint not null comment '应用ID',
  task_no varchar(64) not null comment '发布任务号',
  plan_id varchar(64) not null comment 'DDL计划ID',
  step_no int not null comment 'DDL步骤序号',
  ddl_type varchar(64) not null comment 'DDL类型',
  object_code varchar(64) null comment '对象编码',
  table_name varchar(128) null comment '物理表名',
  column_name varchar(128) null comment '列名',
  sql_template text not null comment '安全DDL模板',
  execute_status varchar(32) not null comment '执行状态：started/success/failed',
  error_code varchar(64) null comment '安全错误码',
  error_message varchar(1024) null comment '安全错误消息',
  trace_id varchar(64) not null comment '追踪ID',
  revision bigint not null default 0 comment '乐观锁版本',
  deleted tinyint not null default 0 comment '软删除标记：0否，1是',
  deleted_at datetime(3) null comment '删除时间',
  delete_token bigint not null default 0 comment '软删除唯一墓碑值',
  create_time datetime(3) not null comment '创建时间',
  create_by bigint not null comment '创建人用户ID',
  update_time datetime(3) not null comment '更新时间',
  update_by bigint not null comment '更新人用户ID',
  primary key (id),
  key idx_lc_rt_ddl_log_task_step (tenant_id, app_id, task_no, step_no)
) comment='运行时DDL执行日志表';

create table lc_meta_publish_task (
  id bigint not null comment '雪花主键',
  tenant_id bigint not null comment '租户ID',
  app_id bigint not null comment '应用ID',
  task_no varchar(64) not null comment '发布任务号',
  source_version varchar(64) null comment '来源版本号',
  target_version varchar(64) not null comment '目标版本号',
  publish_status varchar(32) not null comment '发布状态编码',
  current_step int null comment '当前DDL步骤',
  plan_id varchar(64) null comment 'DDL计划ID',
  plan_json json null comment 'DDL计划快照JSON',
  fencing_token bigint not null default 0 comment '发布fencing令牌',
  meta_hash varchar(128) null comment '目标元数据哈希',
  error_code varchar(64) null comment '安全错误码',
  error_message varchar(1024) null comment '安全错误消息',
  error_detail json null comment '可恢复详情JSON',
  trace_id varchar(64) not null comment '追踪ID',
  revision bigint not null default 0 comment '乐观锁版本',
  deleted tinyint not null default 0 comment '软删除标记：0否，1是',
  deleted_at datetime(3) null comment '删除时间',
  delete_token bigint not null default 0 comment '软删除唯一墓碑值',
  create_time datetime(3) not null comment '创建时间',
  create_by bigint not null comment '创建人用户ID',
  update_time datetime(3) not null comment '更新时间',
  update_by bigint not null comment '更新人用户ID',
  primary key (id),
  unique key uk_lc_meta_publish_task_no_alive (tenant_id, app_id, task_no, delete_token),
  key idx_lc_meta_publish_task_status (tenant_id, app_id, publish_status)
) comment='元数据发布任务表';
