apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins

      # 节点选择器（可选）- 如果有专门的节点
      # nodeSelector:
      #   workload: ci-cd

      # 容忍度（可选）
      # tolerations:
      # - key: "workload"
      #   operator: "Equal"
      #   value: "ci-cd"
      #   effect: "NoSchedule"

      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk21
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 50000
          name: agent
          protocol: TCP

        # 优化后的资源配置
        resources:
          requests:
            cpu: "2"           # 提高到 2 核（原来 1 核）
            memory: 4Gi        # 提高到 4GB（原来 2GB）
          limits:
            cpu: "6"           # 提高到 6 核（原来 3 核）
            memory: 8Gi        # 提高到 8GB（原来 4GB）

        # 优化后的 JVM 参数
        env:
        - name: JAVA_OPTS
          value: >-
            -Xmx6g
            -Xms2g
            -XX:+UseG1GC
            -XX:MaxGCPauseMillis=100
            -XX:+ParallelRefProcEnabled
            -XX:+DisableExplicitGC
            -XX:+AlwaysPreTouch
            -XX:MaxMetaspaceSize=512m
            -Djava.awt.headless=true
            -Dhudson.model.DirectoryBrowserSupport.CSP=
            -Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Shanghai
            -Duser.timezone=Asia/Shanghai

        - name: JENKINS_OPTS
          value: >-
            --sessionTimeout=1440
            --sessionEviction=86400

        # 健康检查
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5

        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        volumeMounts:
        - name: jenkins-storage
          mountPath: /var/jenkins_home

      volumes:
      - name: jenkins-storage
        persistentVolumeClaim:
          claimName: jenkins-pvc

      # 安全上下文
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
