# Docker Registry + UI + Nginx 反向代理（解决跨域问题）
---
apiVersion: v1
kind: Namespace
metadata:
  name: docker-registry

---
# Registry Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: registry
        image: docker.io/library/registry:2
        ports:
        - containerPort: 5000
        env:
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"

---
# Registry Service
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: docker-registry

---
# Registry UI Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      containers:
      - name: ui
        image: joxit/docker-registry-ui:2.5.7
        ports:
        - containerPort: 80
        env:
        - name: REGISTRY_URL
          value: "http://192.168.80.100:30500"
        - name: DELETE_IMAGES
          value: "true"
        - name: SINGLE_REGISTRY
          value: "true"
        - name: REGISTRY_TITLE
          value: "Docker Registry"
        - name: NGINX_PROXY_PASS_URL
          value: "http://docker-registry.docker-registry.svc.cluster.local:5000"

---
# Registry UI Service
apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: docker-registry
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: registry-ui

---
# Nginx ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: docker-registry
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream registry {
            server docker-registry.docker-registry.svc.cluster.local:5000;
        }
        
        upstream ui {
            server registry-ui.docker-registry.svc.cluster.local:80;
        }
        
        server {
            listen 80;
            client_max_body_size 0;
            chunked_transfer_encoding on;
            
            # UI 界面
            location / {
                proxy_pass http://ui;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            # Registry API
            location /v2 {
                # 允许大文件上传
                client_max_body_size 0;
                proxy_request_buffering off;
                
                proxy_pass http://registry/v2;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                # 添加 CORS 头
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Cache-Control,Content-Type' always;
                add_header 'Access-Control-Expose-Headers' 'Docker-Content-Digest' always;
                
                if ($request_method = 'OPTIONS') {
                    return 204;
                }
            }
        }
    }
  
  default.conf: |
    # 空文件，防止默认配置干扰

---
# Nginx Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config

---
# Nginx Service - NodePort
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: docker-registry
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30500
  selector:
    app: nginx-proxy
