upstream api_bakend_wss {
    ip_hash;
    server emqx-54.nms4cloud.svc.cluster.local:8083 max_fails=0 weight=1;
}

server {
    listen 80;
    listen [::]:80;
    server_name gzjj.lmnsaas.com shop.gzjjzhy.com wx.gzjjzhy.com h5.gzjjzhy.com api.gzjjzhy.com mp.gzjjzhy.com;

    gzip on;
    gzip_min_length 1024;
    gzip_buffers 4 16k;
    gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;

    location / {
        root /usr/share/nginx/html/main;
        try_files $uri $uri/ /index.html;
    }

    location /logo.png {
        alias /etc/nginx/conf.d/logo.png;
        access_log off;
        expires 1d;
    }

    location /logo.svg {
        alias /etc/nginx/conf.d/logo.svg;
        access_log off;
        expires 1d;
    }

    location /favicon.ico {
        alias /etc/nginx/conf.d/favicon.ico;
        access_log off;
        expires 1d;
    }

    location /logo/default/logo.png {
        alias /etc/nginx/conf.d/logo.png;
        access_log off;
        expires 1d;
    }

    location /logo/default//logo.svg {
        alias /etc/nginx/conf.d/logo.svg;
        access_log off;
        expires 1d;
    }

    location /logo/default//favicon.ico {
        alias /etc/nginx/conf.d/favicon.ico;
        access_log off;
        expires 1d;
    }

    # location /pictures/ {
    #     root /usr/share/nginx/html;
    #     try_files $uri $uri/ =404;
    # }

    location /mqtt {
        proxy_pass http://api_bakend_wss/mqtt;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Sec-WebSocket-Protocol mqtt;
        proxy_connect_timeout 5s;
        proxy_read_timeout 60000s;
        proxy_send_timeout 60000s;
    }

    location /api/ {
        proxy_pass http://gateway.nms4cloud.svc.cluster.local:8080/api/;
        proxy_redirect default;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        error_page 404 /404.html;
        error_page 500 502 503 504 /50x.html;
    }

    location /spapi/ {
        proxy_pass http://gateway.nms4cloud.svc.cluster.local:8080/api/;
        proxy_redirect default;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        error_page 404 /404.html;
        error_page 500 502 503 504 /50x.html;
    }

    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
