server {
    listen 80;
    listen [::]:80;
    server_name p.clovia.top;

    gzip on;
    gzip_min_length 1024;
    gzip_buffers 4 16k;
    gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;

    location / {
        root /usr/share/nginx/html/pay;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://gateway.nms4cloud.svc.cluster.local:8080/api/;
        proxy_redirect default;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        error_page 404 /404.html;
        error_page 500 502 503 504 /50x.html;
    }

    location /spapi/ {
        proxy_pass http://gateway.nms4cloud.svc.cluster.local:8080/api/;
        proxy_redirect default;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        error_page 404 /404.html;
        error_page 500 502 503 504 /50x.html;
    }

    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
