-- project: nms4pos
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `crm_consume_points_session` (
  `pid` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `mid` BIGINT NOT NULL COMMENT '商户ID',
  `sid` BIGINT NOT NULL COMMENT '门店ID',
  `lid` BIGINT NOT NULL COMMENT '会话逻辑主键',
  `source_` INT NOT NULL COMMENT '积分来源：1-POS',
  `bill_lid` BIGINT DEFAULT NULL COMMENT 'POS账单LID',
  `order_id` VARCHAR(64) DEFAULT NULL COMMENT 'POS订单号',
  `card_no` VARCHAR(64) DEFAULT NULL COMMENT '会员卡号',
  `card_lid` BIGINT NOT NULL COMMENT 'POS本地会员卡LID',
  `current_round_lid` BIGINT DEFAULT NULL COMMENT '当前有效轮次LID',
  `status_` INT DEFAULT NULL COMMENT '会话状态：1-打开，2-闭环，3-失败',
  `revision` INT DEFAULT NULL COMMENT '乐观锁',
  `created_by` VARCHAR(32) DEFAULT NULL COMMENT '创建人',
  `created_time` DATETIME DEFAULT NULL COMMENT '创建时间',
  `updated_by` VARCHAR(32) DEFAULT NULL COMMENT '更新人',
  `updated_time` DATETIME DEFAULT NULL COMMENT '更新时间',
  `deleted` TINYINT DEFAULT 0 COMMENT '是否删除',
  PRIMARY KEY (`pid`),
  UNIQUE KEY `uk_crm_consume_points_session_bill_card` (`mid`, `sid`, `source_`, `bill_lid`, `card_lid`, `deleted`),
  KEY `idx_crm_consume_points_session_bill` (`bill_lid`),
  KEY `idx_crm_consume_points_session_status` (`status_`)
) COMMENT='POS本地消费积分会话';

CREATE TABLE IF NOT EXISTS `crm_consume_points_round` (
  `pid` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `mid` BIGINT NOT NULL COMMENT '商户ID',
  `sid` BIGINT NOT NULL COMMENT '门店ID',
  `lid` BIGINT NOT NULL COMMENT '轮次逻辑主键',
  `session_lid` BIGINT NOT NULL COMMENT '消费积分会话LID',
  `bill_lid` BIGINT DEFAULT NULL COMMENT 'POS账单LID',
  `order_id` VARCHAR(64) DEFAULT NULL COMMENT 'POS订单号',
  `card_no` VARCHAR(64) DEFAULT NULL COMMENT '会员卡号',
  `card_lid` BIGINT NOT NULL COMMENT 'POS本地会员卡LID',
  `round_no` INT DEFAULT NULL COMMENT '轮次序号',
  `parent_round_lid` BIGINT DEFAULT NULL COMMENT '上一轮轮次LID',
  `crm_task_lid` BIGINT DEFAULT NULL COMMENT 'CRM会员卡消费任务LID',
  `grant_points` DECIMAL(18,2) DEFAULT NULL COMMENT '本次消费应赠积分值',
  `current_effective_points` DECIMAL(18,2) DEFAULT NULL COMMENT '当前净有效积分',
  `grant_points_record_lid` BIGINT DEFAULT NULL COMMENT 'CRM发放积分流水LID',
  `revoke_points_record_lid` BIGINT DEFAULT NULL COMMENT 'CRM撤销积分流水LID',
  `rule_lid` BIGINT DEFAULT NULL COMMENT '积分规则LID',
  `eligible_amount_snapshot` DECIMAL(18,2) DEFAULT NULL COMMENT '可积分金额快照',
  `pay_snapshot_json` TEXT COMMENT '支付拆分快照JSON',
  `grant_basis_snapshot_json` TEXT COMMENT '授分依据快照JSON',
  `status_` INT DEFAULT NULL COMMENT '轮次状态',
  `active_flag` TINYINT DEFAULT 0 COMMENT '是否当前有效轮次：0-否，1-是',
  `retry_count` INT DEFAULT NULL COMMENT '重试次数',
  `next_retry_time` DATETIME DEFAULT NULL COMMENT '下次重试时间',
  `last_retry_time` DATETIME DEFAULT NULL COMMENT '最近一次执行时间',
  `last_error_msg` TEXT COMMENT '最近一次失败原因',
  `grant_time` DATETIME DEFAULT NULL COMMENT '成功发放时间',
  `revoke_time` DATETIME DEFAULT NULL COMMENT '成功撤销时间',
  `revision` INT DEFAULT NULL COMMENT '乐观锁',
  `created_by` VARCHAR(32) DEFAULT NULL COMMENT '创建人',
  `created_time` DATETIME DEFAULT NULL COMMENT '创建时间',
  `updated_by` VARCHAR(32) DEFAULT NULL COMMENT '更新人',
  `updated_time` DATETIME DEFAULT NULL COMMENT '更新时间',
  `deleted` TINYINT DEFAULT 0 COMMENT '是否删除',
  `active_session_lid` BIGINT GENERATED ALWAYS AS (CASE WHEN `active_flag` = 1 AND `deleted` = 0 THEN `session_lid` ELSE NULL END) STORED COMMENT '当前有效轮次唯一约束列',
  PRIMARY KEY (`pid`),
  UNIQUE KEY `uk_crm_consume_points_round_session_no` (`session_lid`, `round_no`, `deleted`),
  UNIQUE KEY `uk_crm_consume_points_round_active` (`active_session_lid`),
  KEY `idx_crm_consume_points_round_session` (`session_lid`),
  KEY `idx_crm_consume_points_round_bill` (`bill_lid`),
  KEY `idx_crm_consume_points_round_task` (`crm_task_lid`),
  KEY `idx_crm_consume_points_round_status` (`status_`),
  KEY `idx_crm_consume_points_round_retry` (`next_retry_time`)
) COMMENT='POS本地消费积分轮次';

CREATE TABLE IF NOT EXISTS `crm_consume_points_event` (
  `pid` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `mid` BIGINT NOT NULL COMMENT '商户ID',
  `sid` BIGINT NOT NULL COMMENT '门店ID',
  `lid` BIGINT NOT NULL COMMENT '事件逻辑主键',
  `session_lid` BIGINT DEFAULT NULL COMMENT '消费积分会话LID',
  `round_lid` BIGINT DEFAULT NULL COMMENT '消费积分轮次LID',
  `event_type` INT DEFAULT NULL COMMENT '事件类型',
  `status_` INT DEFAULT NULL COMMENT '事件状态',
  `payload_json` TEXT COMMENT '事件载荷JSON',
  `error_msg` TEXT COMMENT '错误信息',
  `created_by` VARCHAR(32) DEFAULT NULL COMMENT '创建人',
  `created_time` DATETIME DEFAULT NULL COMMENT '创建时间',
  `updated_by` VARCHAR(32) DEFAULT NULL COMMENT '更新人',
  `updated_time` DATETIME DEFAULT NULL COMMENT '更新时间',
  `deleted` TINYINT DEFAULT 0 COMMENT '是否删除',
  PRIMARY KEY (`pid`),
  KEY `idx_crm_consume_points_event_session` (`session_lid`),
  KEY `idx_crm_consume_points_event_round` (`round_lid`)
) COMMENT='POS本地消费积分异事件';

SET FOREIGN_KEY_CHECKS = 1;
