-- project: nms4cloud
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `crm_points_rule`;
CREATE TABLE `crm_points_rule` (
  `pid` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '物理编号',
  `mid` BIGINT NOT NULL COMMENT '商户ID',
  `sid` BIGINT NULL COMMENT '门店ID；兼容字段，积分权益规则当前不按门店隔离，保存时为空',
  `lid` BIGINT NOT NULL COMMENT '逻辑编号(雪花算法)',
  `name` VARCHAR(100) COMMENT '规则名称；当前接口层未开放编辑，通常为空，预留给后台运营展示',
  `plan_lid` BIGINT NOT NULL COMMENT '所属会员方案逻辑编号',
  `points_rule_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '积分规则全局开关:0-否,1-是',
  `earning_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '是否启用消费送积分:0-否,1-是',
  `gift_amount_earn_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '储值赠送参与积分:0-关闭,1-开启',
  `earning_mode` TINYINT COMMENT '积分模式:1-按支付方式实收积分,2-按商品实收积分',
  `earning_product_scope_type` TINYINT COMMENT '获取积分适用商品范围:1-全部商品,2-指定商品参与,3-指定商品不参与',
  `earning_specified_product_lids` JSON COMMENT '获取积分指定商品ID列表(JSON数组)',
  `level_rates` JSON COMMENT '会员等级赠分规则(JSON数组): [{memberLevelId,consumeAmount,earnPoints,sortOrder}]',
  `single_earn_limit_type` TINYINT COMMENT '单笔获取上限类型:1-不限制,2-限制',
  `single_earn_limit_value` DECIMAL(18,2) COMMENT '单笔获取上限积分值',
  `bonus_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '多倍积分总开关:0-否,1-是',
  `birthday_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '生日多倍积分开关:0-否,1-是',
  `birthday_period` TINYINT COMMENT '生日范围:1-当天,2-当周,3-当月',
  `birthday_multiplier` DECIMAL(5,2) COMMENT '生日积分倍数',
  `member_day_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '会员日多倍积分开关:0-否,1-是',
  `member_day_period` TINYINT COMMENT '会员日周期:1-每周,2-每月',
  `member_day_days_of_week` JSON COMMENT '会员日按周生效星期，JSON数字数组，1-周一，2-周二，3-周三，4-周四，5-周五，6-周六，7-周日',
  `member_day_days_of_month` JSON COMMENT '会员日按月生效日期，JSON数字数组，1-31',
  `member_day_multiplier` DECIMAL(5,2) COMMENT '会员日积分倍数',
  `available_cycle` TINYINT COMMENT '获取积分可用周期:1-按日,2-按周,3-按月',
  `available_days_of_week` JSON COMMENT '获取积分按周生效星期，JSON数字数组，1-周一，2-周二，3-周三，4-周四，5-周五，6-周六，7-周日',
  `available_days_of_month` JSON COMMENT '获取积分按月生效日期，JSON数字数组，1-31',
  `available_time_type` TINYINT COMMENT '获取积分可用时段类型:1-全天,2-指定时段',
  `available_time_slots` JSON COMMENT '获取积分指定时段(JSON数组)',
  `wecom_exclusive_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '企微会员专享开关:0-否,1-是',
  `wecom_exclusive_type` TINYINT COMMENT '企微会员专享类型:1-好友或群客,2-好友,3-群客,4-好友且群客',
  `order_scene_limit` JSON COMMENT '获取积分订单场景限制，JSON数字数组，1-堂食，2-外卖，3-自提，4-外带',
  `order_channel_limit` JSON COMMENT '获取积分订单渠道限制，JSON数字数组，1-门店POS，2-微信小程序，3-支付宝小程序，4-抖音小程序，5-商户中心，6-自助大屏，7-码牌收银',
  `deduction_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '是否启用积分抵现:0-否,1-是',
  `deduction_rate` DECIMAL(18,4) COMMENT '积分抵扣比例(X积分=1元)',
  `min_deduction_type` TINYINT COMMENT '起扣积分限制类型:1-不限制,2-限制',
  `min_deduction_value` DECIMAL(18,2) COMMENT '起扣积分数',
  `deduction_multiple_type` TINYINT COMMENT '抵扣倍数类型:1-不限制,2-限制',
  `deduction_multiple_value` INT COMMENT '抵扣整数倍数值',
  `deduction_rounding` TINYINT COMMENT '抵扣金额取整:1-不取整,2-向下取整',
  `deduction_ceiling_type` TINYINT COMMENT '抵扣上限类型:1-不限制,2-固定积分,3-账单比例',
  `deduction_ceiling_points` DECIMAL(18,2) COMMENT '固定积分上限',
  `deduction_ceiling_ratio` DECIMAL(5,2) COMMENT '账单比例上限，单位%',
  `deduct_cycle` TINYINT COMMENT '积分抵现可用周期:1-按日,2-按周,3-按月',
  `deduct_days_of_week` JSON COMMENT '积分抵现按周生效星期，JSON数字数组，1-周一，2-周二，3-周三，4-周四，5-周五，6-周六，7-周日',
  `deduct_days_of_month` JSON COMMENT '积分抵现按月生效日期，JSON数字数组，1-31',
  `deduct_time_type` TINYINT COMMENT '积分抵现可用时段类型:1-全天,2-指定时段',
  `deduct_time_slots` JSON COMMENT '积分抵现指定时段(JSON数组)',
  `product_limit_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '抵现商品限制开关:0-否,1-是',
  `product_scope_type` TINYINT COMMENT '抵现商品范围:2-指定商品参与,3-指定商品不参与,4-指定分类参与,5-指定分类不参与',
  `deduct_specified_product_lids` JSON COMMENT '抵现指定商品ID列表(JSON数组)',
  `deduct_pos_category_lids` JSON COMMENT '抵现POS分类ID列表(JSON数组)',
  `deduct_miniapp_category_lids` JSON COMMENT '抵现小程序分类ID列表(JSON数组)',
  `deduct_exclude_product_lids` JSON COMMENT '抵现排除商品ID列表(JSON数组)',
  `deduct_scene_limit` JSON COMMENT '抵现订单场景限制，JSON数字数组，1-堂食，2-外卖，3-自提，4-外带',
  `deduct_channel_limit` JSON COMMENT '抵现订单渠道限制，JSON数字数组，1-门店POS，2-微信小程序，3-支付宝小程序，4-抖音小程序，5-商户中心，6-自助大屏，7-码牌收银',
  `expiry_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '是否启用积分清零:0-否,1-是',
  `expiry_mode` TINYINT COMMENT '清零模式:1-自发放日期,2-年度清零',
  `expiry_duration` VARCHAR(20) COMMENT '自发放清零时限；expiry_mode=1 时有值',
  `expiry_frequency` TINYINT COMMENT '清零频次:1-日清,2-月清；expiry_mode=1 时有值',
  `expiry_annual_years` INT COMMENT '年度清零下N年；expiry_mode=2 时有值',
  `expiry_annual_date` VARCHAR(20) COMMENT '年度清零日期；expiry_mode=2 时有值',
  `expiry_notify_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '积分清零提醒开关:0-否,1-是',
  `expiry_remind_days` INT COMMENT '提前通知天数；expiry_notify_enabled=1 时有值',
  `rule_description` VARCHAR(600) COMMENT '积分规则公示说明',
  `created_by` VARCHAR(100) COMMENT '创建人',
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` VARCHAR(100) COMMENT '更新人',
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除(0-否,1-是)',
  `revision` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号'
) COMMENT='积分权益规则主表';

CREATE INDEX `idx_mid` ON `crm_points_rule`(`mid`);
CREATE UNIQUE INDEX `uk_lid` ON `crm_points_rule`(`lid`);
CREATE INDEX `idx_plan_lid` ON `crm_points_rule`(`plan_lid`);
CREATE UNIQUE INDEX `uk_mid_plan_lid` ON `crm_points_rule`(`mid`, `plan_lid`);

SET FOREIGN_KEY_CHECKS = 1;
