CREATE TABLE IF NOT EXISTS `crm_consume_cash_op_record` (
  `pid` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `mid` BIGINT NOT NULL COMMENT '商户ID',
  `sid` BIGINT NOT NULL COMMENT '门店ID',
  `lid` BIGINT NOT NULL COMMENT '业务逻辑主键',
  `round_key` VARCHAR(128) NOT NULL COMMENT 'POS返现轮次幂等键',
  `order_id` VARCHAR(64) DEFAULT NULL COMMENT 'POS外部订单号',
  `card_lid` BIGINT DEFAULT NULL COMMENT '会员卡LID',
  `card_no` VARCHAR(64) DEFAULT NULL COMMENT '会员卡号',
  `status_` INT NOT NULL COMMENT '状态：1-待处理，2-已返现，3-未命中，4-已撤销，5-失败',
  `rule_lid` BIGINT DEFAULT NULL COMMENT '消费返现规则LID',
  `bill_amount` DECIMAL(18,2) DEFAULT NULL COMMENT '参与返现的消费金额快照',
  `check_out_time` DATETIME DEFAULT NULL COMMENT 'POS结账时间快照，用于幂等校验和返现规则有效期判定',
  `cash_back_amount` DECIMAL(18,2) DEFAULT NULL COMMENT '本次返现金额',
  `task_lid` BIGINT DEFAULT NULL COMMENT 'CRM返现任务LID',
  `balance_record_lid` BIGINT DEFAULT NULL COMMENT '会员余额流水LID',
  `request_json` TEXT COMMENT '返现请求快照JSON',
  `response_json` TEXT COMMENT '最近一次响应快照JSON',
  `error_msg` TEXT COMMENT '最近一次失败原因',
  `grant_time` DATETIME DEFAULT NULL COMMENT '成功返现时间',
  `revoke_time` DATETIME DEFAULT NULL COMMENT '成功撤销时间',
  `revision` INT DEFAULT NULL COMMENT '乐观锁',
  `created_by` VARCHAR(32) DEFAULT NULL COMMENT '创建人',
  `created_time` DATETIME DEFAULT NULL COMMENT '创建时间',
  `updated_by` VARCHAR(32) DEFAULT NULL COMMENT '更新人',
  `updated_time` DATETIME DEFAULT NULL COMMENT '更新时间',
  `deleted` TINYINT DEFAULT 0 COMMENT '是否删除',
  PRIMARY KEY (`pid`),
  UNIQUE KEY `uk_crm_consume_cash_op_lid` (`lid`),
  UNIQUE KEY `uk_crm_consume_cash_op_round` (`mid`, `sid`, `round_key`, `deleted`),
  KEY `idx_crm_consume_cash_op_order` (`mid`, `order_id`),
  KEY `idx_crm_consume_cash_op_status` (`status_`)
) COMMENT='CRM消费返现POS轮次幂等记录';
