apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-sync-script
  namespace: harbor
data:
  sync.sh: |
    #!/bin/bash
    set -e
    
    # Harbor 配置
    HARBOR_REGISTRY="harbor-core.harbor"
    HARBOR_PROJECT="library"
    HARBOR_USERNAME="admin"
    HARBOR_PASSWORD="Harbor12345"
    
    # 阿里云配置
    ALIYUN_REGISTRY="crpi-csgbt2t7j15cj178.cn-hangzhou.personal.cr.aliyuncs.com"
    ALIYUN_NAMESPACE="lgy-images"
    ALIYUN_USERNAME="abcliu110"
    ALIYUN_PASSWORD="st11338st11338"
    
    echo "=== Harbor 镜像同步到阿里云 ==="
    echo "时间: $(date)"
    
    # 登录 Harbor
    echo ">>> 登录 Harbor..."
    echo "${HARBOR_PASSWORD}" | docker login ${HARBOR_REGISTRY} \
        --username ${HARBOR_USERNAME} \
        --password-stdin
    
    # 登录阿里云
    echo ">>> 登录阿里云..."
    echo "${ALIYUN_PASSWORD}" | docker login ${ALIYUN_REGISTRY} \
        --username ${ALIYUN_USERNAME} \
        --password-stdin
    
    # 获取 Harbor 中的镜像列表（需要根据实际情况调整）
    IMAGES=(
        "demo-springboot:latest"
    )
    
    SUCCESS=0
    FAIL=0
    
    for IMAGE in "${IMAGES[@]}"; do
        IMAGE_NAME=$(echo $IMAGE | cut -d: -f1)
        IMAGE_TAG=$(echo $IMAGE | cut -d: -f2)
        
        HARBOR_IMAGE="${HARBOR_REGISTRY}/${HARBOR_PROJECT}/${IMAGE_NAME}:${IMAGE_TAG}"
        ALIYUN_IMAGE="${ALIYUN_REGISTRY}/${ALIYUN_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}"
        
        echo ""
        echo ">>> 同步: ${IMAGE_NAME}:${IMAGE_TAG}"
        
        # 拉取
        if docker pull ${HARBOR_IMAGE}; then
            # 标记
            docker tag ${HARBOR_IMAGE} ${ALIYUN_IMAGE}
            
            # 推送
            if docker push ${ALIYUN_IMAGE}; then
                echo "✓ 同步成功"
                SUCCESS=$((SUCCESS + 1))
                
                # 清理
                docker rmi ${HARBOR_IMAGE} ${ALIYUN_IMAGE} 2>/dev/null || true
            else
                echo "❌ 推送失败"
                FAIL=$((FAIL + 1))
            fi
        else
            echo "❌ 拉取失败"
            FAIL=$((FAIL + 1))
        fi
    done
    
    echo ""
    echo "=== 同步完成 ==="
    echo "成功: ${SUCCESS}"
    echo "失败: ${FAIL}"
    echo "时间: $(date)"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: harbor-sync-to-aliyun
  namespace: harbor
spec:
  # 每天凌晨 2 点执行
  schedule: "0 2 * * *"
  # 或者每小时执行一次
  # schedule: "0 * * * *"
  
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          
          containers:
          - name: sync
            image: docker:24-dind
            command:
            - /bin/sh
            - -c
            - |
              # 启动 Docker daemon
              dockerd-entrypoint.sh &
              sleep 10
              
              # 执行同步脚本
              /scripts/sync.sh
            
            volumeMounts:
            - name: script
              mountPath: /scripts
            
            # 需要特权模式运行 Docker
            securityContext:
              privileged: true
            
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
          
          volumes:
          - name: script
            configMap:
              name: harbor-sync-script
              defaultMode: 0755
