apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-console
  namespace: nms4cloud
  labels: {}
spec:
  selector:
    matchLabels:
      app: rocketmq-console
  template:
    metadata:
      labels:
        app: rocketmq-console
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Drocketmq.namesrv.addr=rocketmq-nameserver:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
        image: apacherocketmq/rocketmq-console:2.0.0
        imagePullPolicy: IfNotPresent
        name: console
        ports:
        - containerPort: 8080
          hostPort: 8080
          name: console
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 512Mi
