apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-broker
  namespace: nms4cloud
  labels: {}
spec:
  selector:
    matchLabels:
      app: rocketmq-broker
  template:
    metadata:
      labels:
        app: rocketmq-broker
    spec:
      containers:
      - command:
        - sh
        - mqbroker
        - -n
        - rocketmq-nameserver:9876
        env:
        - name: JAVA_OPT_EXT
          value: -Xms256m -Xmx256m
        image: apache/rocketmq:5.1.0
        imagePullPolicy: IfNotPresent
        name: broker
        ports:
        - containerPort: 10909
          hostPort: 10909
          name: vip
          protocol: TCP
        - containerPort: 10911
          hostPort: 10911
          name: main
          protocol: TCP
        - containerPort: 10912
          hostPort: 10912
          name: ha
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
