apiVersion: v1
kind: Secret
metadata:
  name: merged-registry-secret
  namespace: jenkins
type: kubernetes.io/dockerconfigjson
data:
  # 包含 Harbor 和阿里云两个仓库的认证信息
  # 解码后的内容：
  # {
  #   "auths": {
  #     "harbor-core.harbor": {
  #       "username": "admin",
  #       "password": "Harbor12345",
  #       "auth": "YWRtaW46SGFyYm9yMTIzNDU="
  #     },
  #     "crpi-csgbt2t7j15cj178.cn-hangzhou.personal.cr.aliyuncs.com": {
  #       "username": "abcliu110",
  #       "password": "st11338st11338",
  #       "auth": "YWJjbGl1MTEwOnN0MTEzMzhzdDExMzM4"
  #     }
  #   }
  # }
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3ItY29yZS5oYXJib3IiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiSGFyYm9yMTIzNDUiLCJhdXRoIjoiWVdSdGFXNDZTR0Z5WW05eU1USXpORFU9In0sImNycGktY3NnYnQydDdqMTVjajE3OC5jbi1oYW5nemhvdS5wZXJzb25hbC5jci5hbGl5dW5jcy5jb20iOnsidXNlcm5hbWUiOiJhYmNsaXUxMTAiLCJwYXNzd29yZCI6InN0MTEzMzhzdDExMzM4IiwiYXV0aCI6IllXSmpiR2wxTVRFd09uTjBNVEV6TXpoemRERXhNek00In19fQ==
