apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-client
data:
  TZ: Asia/Shanghai
  SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR: nacos.nacos.svc.cluster.local.:8848
  SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: nacos.nacos.svc.cluster.local.:8848
  SPRING_CLOUD_NACOS_CONFIG_NAMESPACE: public
