server:
  port: 80
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.0.1.18:3306/a_mall?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: nms4cloud
    password: Rm_.qwdNdQV3w64ijMAWbmjZu
  cloud:
    config:
      enabled: false
    nacos:
      config:
        file-extension: yaml 
        shared-configs:
          - data-id: nms4cloud-shared.yaml
  




logstash:
  destination: 172.16.0.14:35044

