spring:
  cloud:
    # sentinel:
    #   # filter:
    #   #   enabled: false
    #   transport:
    #     dashboard: sentinel:8858
    #     port: 9998
    #   datasource:
    #     ds1:
    #       nacos:
    #         server-addr: 192.168.1.118:8848
    #         data-id: ${spring.application.name}.json
    #         group-id: DEFAULT_GROUP
    #         data-type: json
    #         rule-type: flow

  redis:
    host: 192.168.1.118
    port: 6379
    database: 0
    password: 123456
    lettuce:
      pool:
        max-active: -1
        min-idle: 5
        max-idle: 10
        max-wait: 5000

  data:
    redis:
      host: 192.168.1.118
      port: 6379
      database: 0
      password: 123456
      lettuce:
        pool:
          max-active: -1
          min-idle: 5
          max-idle: 10
          max-wait: 5000
    redis2:
      host: 192.168.1.118
      port: 6379
      database: 0
      password: 123456
      lettuce:
        pool:
          max-active: -1
          min-idle: 5
          max-idle: 10
          max-wait: 5000    
oss:
  endpoint: https://cos.ap-guangzhou.myqcloud.com
  region: ap-guangzhou
  accessKey: AKIDYw61g6hPEo8D2bfzoOyLUO4VihRxuJ9l
  secretKey: XrxoQmwsZ2HJ7h28zc0A7qJXWFjyyqVx
  bucketName: chain-pictures-01-1251303505
  bucket: 
    # report: web-for-nginx-1251303505
    report: chain-pictures-01-1251303505

rocketmq:
  name-server: 192.168.1.118:9876
  producer: 
    group: ${spring.application.name}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true



nms:
  mybatis:
    encryptor:
      password: e3c38c130eb6d2b716df5f7034ce8f37
  mqtt:
    url: tcp://api.lmnsaas.com:1883
    userName: nmsjb001
    password: nmsjb001
  wxLink: https://wx.gzjjzhy.com


forest:
  backend: okhttp3             # åç«¯HTTPæ¡†æ¶ï¼ˆé»˜è®¤ä¸º okhttp3ï¼?  max-connections: 1000        # è¿æ¥æ± æœ€å¤§è¿æ¥æ•°ï¼ˆé»˜è®¤ä¸º 500ï¼?  max-route-connections: 500   # æ¯ä¸ªè·¯ç”±çš„æœ€å¤§è¿æ¥æ•°ï¼ˆé»˜è®¤ä¸º 500ï¼?  max-request-queue-size: 100  # [è‡ªv1.5.22ç‰ˆæœ¬èµ·å¯ç”¨] æœ€å¤§è¯·æ±‚ç­‰å¾…é˜Ÿåˆ—å¤§å°?  max-async-thread-size: 300   # [è‡ªv1.5.21ç‰ˆæœ¬èµ·å¯ç”¨] æœ€å¤§å¼‚æ­¥çº¿ç¨‹æ•°
  max-async-queue-size: 16     # [è‡ªv1.5.22ç‰ˆæœ¬èµ·å¯ç”¨] æœ€å¤§å¼‚æ­¥çº¿ç¨‹æ± é˜Ÿåˆ—å¤§å°
  timeout: 3000                # [å·²ä¸æ¨èä½¿ç”¨] è¯·æ±‚è¶…æ—¶æ—¶é—´ï¼Œå•ä½ä¸ºæ¯«ç§’ï¼ˆé»˜è®¤ä¸º 3000ï¼?  connect-timeout: 3000        # è¿æ¥è¶…æ—¶æ—¶é—´ï¼Œå•ä½ä¸ºæ¯«ç§’ï¼ˆé»˜è®¤ä¸º timeoutï¼?  read-timeout: 3000           # æ•°æ®è¯»å–è¶…æ—¶æ—¶é—´ï¼Œå•ä½ä¸ºæ¯«ç§’ï¼ˆé»˜è®¤ä¸º timeoutï¼?  max-retry-count: 0           # è¯·æ±‚å¤±è´¥åé‡è¯•æ¬¡æ•°ï¼ˆé»˜è®¤ä¸?0 æ¬¡ä¸é‡è¯•ï¼?  ssl-protocol: TLS            # å•å‘éªŒè¯çš„HTTPSçš„é»˜è®¤TLSåè®®ï¼ˆé»˜è®¤ä¸º TLSï¼?  log-enabled: false            # æ‰“å¼€æˆ–å…³é—­æ—¥å¿—ï¼ˆé»˜è®¤ä¸?trueï¼?  log-request: false            # æ‰“å¼€/å…³é—­Forestè¯·æ±‚æ—¥å¿—ï¼ˆé»˜è®¤ä¸º trueï¼?  log-response-status: false    # æ‰“å¼€/å…³é—­Forestå“åº”çŠ¶æ€æ—¥å¿—ï¼ˆé»˜è®¤ä¸?trueï¼?  log-response-content: false   # æ‰“å¼€/å…³é—­Forestå“åº”å†…å®¹æ—¥å¿—ï¼ˆé»˜è®¤ä¸º falseï¼?  async-mode: platform         # [è‡ªv1.5.27ç‰ˆæœ¬èµ·å¯ç”¨] å¼‚æ­¥æ¨¡å¼ï¼ˆé»˜è®¤ä¸º platformï¼?

piao_tong:
  password: Jj1cy1ZpCq0b36So4dGHZI1P
  platform_code: LVP35v9v
  platform_alias: YDRJ
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCJkx3HelhEm/U7jOCor29oHsIjCMSTyKbX5rpoAY8KDIs9mmr5Y9r+jvNJH8pK3u5gNnvleT6rQgJQW1mk0zHuPO00vy62tSA53fkSjtM+n0oC1Fkm4DRFd5qJgoP7uFQHR5OEffMjy2qIuxChY4Au0kq+6RruEgIttb7wUxy8TwIDAQAB
  privateKey: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAIVLAoolDaE7m5oMB1ZrILHkMXMF6qmC8I/FCejz4hwBcj59H3rbtcycBEmExOJTGwexFkNgRakhqM+3uP3VybWu1GBYNmqVzggWKKzThul9VPE3+OTMlxeG4H63RsCO1//J0MoUavXMMkL3txkZBO5EtTqek182eePOV8fC3ZxpAgMBAAECgYBp4Gg3BTGrZaa2mWFmspd41lK1E/kPBrRA7vltMfPj3P47RrYvp7/js/Xv0+d0AyFQXcjaYelTbCokPMJT1nJumb2A/Cqy3yGKX3Z6QibvByBlCKK29lZkw8WVRGFIzCIXhGKdqukXf8RyqfhInqHpZ9AoY2W60bbSP6EXj/rhNQJBAL76SmpQOrnCI8Xu75di0eXBN/bE9tKsf7AgMkpFRhaU8VLbvd27U9vRWqtu67RY3sOeRMh38JZBwAIS8tp5hgcCQQCyrOS6vfXIUxKoWyvGyMyhqoLsiAdnxBKHh8tMINo0ioCbU+jc2dgPDipL0ym5nhvg5fCXZC2rvkKUltLEqq4PAkAqBf9b932EpKCkjFgyUq9nRCYhaeP6JbUPN3Z5e1bZ3zpfBjV4ViE0zJOMB6NcEvYpy2jNR/8rwRoUGsFPq8//AkAklw18RJyJuqFugsUzPznQvad0IuNJV7jnsmJqo6ur6NUvef6NA7ugUalNv9+imINjChO8HRLRQfRGk6B0D/P3AkBt54UBMtFefOLXgUdilwLdCUSw4KpbuBPw+cyWlMjcXCkj4rHoeksekyBH1GrBJkLqDMRqtVQUubuFwSzBAtlc




jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: com.alibaba
  local:
    default:
      type: caffeine
      limit: 100
      keyConvertor: fastjson2 #å…¶ä»–å¯é€‰ï¼šfastjson/jackson
      expireAfterWriteInMillis: 100000
    otherArea:
      type: linkedhashmap
      limit: 100
      keyConvertor: none
      expireAfterWriteInMillis: 100000
  remote:
    default:
      type: redisson
      keyConvertor: fastjson2 #å…¶ä»–å¯é€‰ï¼šfastjson/jackson
      # broadcastChannel: projectA
      valueEncoder: java #å…¶ä»–å¯é€‰ï¼škryo/kryo5
      valueDecoder: java #å…¶ä»–å¯é€‰ï¼škryo/kryo5
