server:
  port: 80
spring:
  # datasource:
  #   driverClassName: com.mysql.jdbc.Driver
  #   type: com.zaxxer.hikari.HikariDataSource
  #   url: jdbc:mysql://10.0.1.18:3306/a_docking?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
  #   username: nms4cloud
  #   password: Rm_.qwdNdQV3w64ijMAWbmjZu
  datasource:
    dynamic:
      primary: clickhouse #è®¾ç½®é»˜è®¤çš„æ•°æ®æºæˆ–è€…æ•°æ®æºç»?é»˜è®¤å€¼å³ä¸ºmaster
      strict: false #ä¸¥æ ¼åŒ¹é…æ•°æ®æº?é»˜è®¤false. trueæœªåŒ¹é…åˆ°æŒ‡å®šæ•°æ®æºæ—¶æŠ›å¼‚å¸?falseä½¿ç”¨é»˜è®¤æ•°æ®æº?      datasource:
        docking:
          url: jdbc:mysql://10.0.1.18:3306/a_docking?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
          username: nms4cloud
          password: Rm_.qwdNdQV3w64ijMAWbmjZu
          driverClassName: com.mysql.jdbc.Driver
          # type: com.zaxxer.hikari.HikariDataSource
        mycat:
          url: jdbc:mysql://mycat-saas:8066/LMN_CHAIN?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
          username: root
          password: 8HsvuRr_z4iq_gXb
          driverClassName: com.mysql.jdbc.Driver
        clickhouse:
          url: jdbc:clickhouse://clickhouse:8123/nms4cloud?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&useTimeZone=true&serverTimezone=Asia/Shanghai
          username: 
          password: 
          driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
          # type: com.zaxxer.hikari.HikariDataSource
  cloud:
    config:
      enabled: false
    nacos:
      config:
        file-extension: yaml 
        shared-configs:
          - data-id: nms4cloud-shared.yaml
  

# nms:
#   common:
#     mybatis-flex-enabled: true
#     show_sql_for_debug: true

# mybatis-plus:
#   configuration:
#     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logstash:
  destination: 172.16.0.14:35044

